<?php echo $header; ?><?php echo $column_left; ?>
<div id="content">
  <div class="page-header"><div class="container-fluid">
    <div class="pull-right"><button type="submit" form="form-anchor-price" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-primary"><i class="fa fa-save"></i></button><a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
    <h1><?php echo $heading_title; ?></h1><ul class="breadcrumb"><?php foreach ($breadcrumbs as $breadcrumb) { ?><li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li><?php } ?></ul>
  </div></div>
  <div class="container-fluid">
    <?php if ($error_warning) { ?><div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> <?php echo htmlspecialchars($error_warning, ENT_QUOTES, 'UTF-8'); ?><button type="button" class="close" data-dismiss="alert">&times;</button></div><?php } ?>
    <div class="panel panel-default">
      <div class="panel-heading"><h3 class="panel-title"><i class="fa fa-pencil"></i> <?php echo $text_edit; ?> — <?php echo htmlspecialchars($anchor['product_name'], ENT_QUOTES, 'UTF-8'); ?></h3></div>
      <div class="panel-body">
        <div class="alert alert-info"><strong>ID <?php echo (int)$anchor['product_id']; ?></strong> · <?php echo htmlspecialchars($anchor['model'], ENT_QUOTES, 'UTF-8'); ?> · <?php echo htmlspecialchars($anchor['currency_code'], ENT_QUOTES, 'UTF-8'); ?><br /><small><?php echo htmlspecialchars($anchor['rule_code'], ENT_QUOTES, 'UTF-8'); ?> / <?php echo htmlspecialchars($anchor['source'], ENT_QUOTES, 'UTF-8'); ?></small></div>
        <form action="<?php echo $action; ?>" method="post" id="form-anchor-price" class="form-horizontal">
          <div class="form-group required"><label class="col-sm-2 control-label" for="input-price"><?php echo $entry_price; ?></label><div class="col-sm-10"><div class="input-group"><input type="text" name="price" value="<?php echo htmlspecialchars($price, ENT_QUOTES, 'UTF-8'); ?>" id="input-price" class="form-control" /><span class="input-group-addon"><?php echo htmlspecialchars($anchor['currency_code'], ENT_QUOTES, 'UTF-8'); ?></span></div><?php if ($error_price) { ?><div class="text-danger"><?php echo $error_price; ?></div><?php } ?></div></div>
          <div class="form-group required"><label class="col-sm-2 control-label" for="input-gross-price"><span data-toggle="tooltip" title="<?php echo htmlspecialchars($help_gross_price, ENT_QUOTES, 'UTF-8'); ?>"><?php echo $entry_gross_price; ?></span></label><div class="col-sm-10"><div class="input-group"><input type="text" name="gross_price" value="<?php echo htmlspecialchars($gross_price, ENT_QUOTES, 'UTF-8'); ?>" id="input-gross-price" class="form-control" /><span class="input-group-addon"><?php echo htmlspecialchars($anchor['currency_code'], ENT_QUOTES, 'UTF-8'); ?></span></div><?php if ($error_gross_price) { ?><div class="text-danger"><?php echo $error_gross_price; ?></div><?php } ?></div></div>
          <div class="form-group required"><label class="col-sm-2 control-label" for="input-reference-date"><?php echo $entry_reference_date; ?></label><div class="col-sm-10"><input type="date" name="reference_date" value="<?php echo htmlspecialchars($reference_date, ENT_QUOTES, 'UTF-8'); ?>" id="input-reference-date" class="form-control" /><?php if ($error_reference_date) { ?><div class="text-danger"><?php echo $error_reference_date; ?></div><?php } ?></div></div>
          <div class="form-group required"><label class="col-sm-2 control-label" for="input-status"><?php echo $entry_verification_status; ?></label><div class="col-sm-10"><select name="verification_status" id="input-status" class="form-control"><?php foreach ($statuses as $status_code => $status_name) { ?><option value="<?php echo $status_code; ?>"<?php echo $verification_status === $status_code ? ' selected="selected"' : ''; ?>><?php echo $status_name; ?></option><?php } ?></select><?php if ($error_status) { ?><div class="text-danger"><?php echo $error_status; ?></div><?php } ?></div></div>
          <div class="form-group required"><label class="col-sm-2 control-label" for="input-reason"><span data-toggle="tooltip" title="<?php echo htmlspecialchars($help_reason, ENT_QUOTES, 'UTF-8'); ?>"><?php echo $entry_reason; ?></span></label><div class="col-sm-10"><textarea name="reason" rows="3" maxlength="255" id="input-reason" class="form-control"><?php echo htmlspecialchars($reason, ENT_QUOTES, 'UTF-8'); ?></textarea><?php if ($error_reason) { ?><div class="text-danger"><?php echo $error_reason; ?></div><?php } ?></div></div>
        </form>
      </div>
    </div>
    <div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title"><i class="fa fa-history"></i> <?php echo $text_audit; ?></h3></div><div class="panel-body"><div class="table-responsive"><table class="table table-bordered table-hover">
      <thead><tr><td><?php echo $column_date_added; ?></td><td><?php echo $column_user; ?></td><td><?php echo $column_action; ?></td><td><?php echo $column_reason; ?></td><td><?php echo $column_before; ?></td><td><?php echo $column_after; ?></td></tr></thead>
      <tbody><?php if ($audits) { foreach ($audits as $audit) { ?><tr><td><?php echo $audit['date_added']; ?></td><td><?php echo htmlspecialchars($audit['username'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($audit['action'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($audit['reason'], ENT_QUOTES, 'UTF-8'); ?></td><td><small><?php echo htmlspecialchars($audit['old_summary'], ENT_QUOTES, 'UTF-8'); ?></small></td><td><small><?php echo htmlspecialchars($audit['new_summary'], ENT_QUOTES, 'UTF-8'); ?></small></td></tr><?php } } else { ?><tr><td colspan="6" class="text-center"><?php echo $text_no_results; ?></td></tr><?php } ?></tbody>
    </table></div></div></div>
  </div>
</div>
<?php echo $footer; ?>
